{{- range .Values.clusterRoleBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}
{{- with .roleRef }}
roleRef:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .subjects }}
subjects:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{ end }}