{{- range .Values.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- with .data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
