{{- range .Values.serviceAccount }}
{{- if .create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    {{- include "webchart.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
automountServiceAccountToken: {{ .automount }}
{{- end }}
{{- end }}