apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otus-cred
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: otus-cred
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: "otus/cred"
  # data:
  # - secretKey: username
  #   remoteRef:
  #     key: otus/data/cred
  #     property: username
  # - secretKey: password
  #   remoteRef:
  #     key: otus/data/cred
  #     property: password
