apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bucket-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  bucket: bucket-s3-01
  csi.storage.k8s.io/provisioner-secret-name: bucket-s3-creds
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: bucket-s3-creds
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: bucket-s3-creds
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: bucket-s3-creds
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  # folderId: b1g5h8d28qvg63eps3ms
  zone: ru-central1-d
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
