apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: homework
spec:
  storageClassName: web-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
