# Конфигурация для Development окружения
global:
  kafkaNamespace: dev

# replicaCount: 3

image:
  repository: bitnamilegacy/kafka
  tag: 4.0.0-debian-12-r10
  # tag: 4.0.0

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  saslMechanisms: plain
  saslInterBrokerMechanism: plain
  
  # Отключаем авторизацию
  clientUsers: []
  clientPasswords: []

controller:
  replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

# # Автоматическое создание топиков для разработки
# extraEnvVars:
#   - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
#     value: "true"