apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:1.29.1
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "0.2"
        memory: 256Mi
    command: ["/bin/sh","-c"]
    args: ["sed -i 's/listen  .*/listen 8000;/g' /etc/nginx/conf.d/default.conf && sed -i 's|root  .*|root /homework;|g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ['rm', '-f', '/homework/index.html']
  initContainers:
  - name: initcontainer
    image: busybox:1.28
    command: ["/bin/sh","-c"]
    args: ["wget -O /init/index.html https://otus.ru"]
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}
